SELECT 
	R.ROUTINE_CATALOG AS CATALOGUE,
	R.ROUTINE_SCHEMA AS [SCHEMA],
	R.ROUTINE_NAME AS NAME,
	R.CREATED AS DATE_CREATION,
	R.LAST_ALTERED AS DATE_MODIFICATION
FROM 
	INFORMATION_SCHEMA.ROUTINES R
WHERE 
	R.ROUTINE_TYPE = 'PROCEDURE'
	AND LEFT(R.ROUTINE_NAME, 3) NOT IN ('sp_', 'xp_', 'ms_')
	AND LEFT(R.ROUTINE_NAME, 3) = 'sq_'
ORDER BY 
	R.ROUTINE_NAME;