SELECT A.* FROM 
( SELECT 'CODE_SOCIETE' as NomColonne, COUNT(DISTINCT E.CODE_SOCIETE) AS NombreValeursDistinctes,
COUNT(E.CODE_SOCIETE) AS NombreDeLignes,
(CAST(COUNT(DISTINCT E.CODE_SOCIETE) AS DECIMAL) / CAST(COUNT(E.CODE_SOCIETE) AS DECIMAL)) AS Selectivite,
(1.0/(COUNT(DISTINCT E.CODE_SOCIETE))) AS Densite
FROM REF_PRE.REF.BASE_FACTURATION AS E
UNION ALL 
SELECT 'NUMERO_CA' as NomColonne, COUNT(DISTINCT E.NUMERO_CA) AS NombreValeursDistinctes,
COUNT(E.NUMERO_CA) AS NombreDeLignes,
(CAST(COUNT(DISTINCT E.NUMERO_CA) AS DECIMAL) / CAST(COUNT(E.NUMERO_CA) AS DECIMAL)) AS Selectivite,
(1.0/(COUNT(DISTINCT E.NUMERO_CA))) AS Densite
FROM REF_PRE.REF.BASE_FACTURATION AS E
UNION ALL 
SELECT 'NUMERO_UG' as NomColonne, COUNT(DISTINCT E.NUMERO_UG) AS NombreValeursDistinctes,
COUNT(E.NUMERO_UG) AS NombreDeLignes,
(CAST(COUNT(DISTINCT E.NUMERO_UG) AS DECIMAL) / CAST(COUNT(E.NUMERO_UG) AS DECIMAL)) AS Selectivite,
(1.0/(COUNT(DISTINCT E.NUMERO_UG))) AS Densite
FROM REF_PRE.REF.BASE_FACTURATION AS E
UNION ALL 
SELECT 'CODE_TANTIEME' as NomColonne, COUNT(DISTINCT E.CODE_TANTIEME) AS NombreValeursDistinctes,
COUNT(E.CODE_TANTIEME) AS NombreDeLignes,
(CAST(COUNT(DISTINCT E.CODE_TANTIEME) AS DECIMAL) / CAST(COUNT(E.CODE_TANTIEME) AS DECIMAL)) AS Selectivite,
(1.0/(COUNT(DISTINCT E.CODE_TANTIEME))) AS Densite
FROM REF_PRE.REF.BASE_FACTURATION AS E
UNION ALL 
SELECT 'DATE_DEBUT_VALIDITE' as NomColonne, COUNT(DISTINCT E.DATE_DEBUT_VALIDITE) AS NombreValeursDistinctes,
COUNT(E.DATE_DEBUT_VALIDITE) AS NombreDeLignes,
(CAST(COUNT(DISTINCT E.DATE_DEBUT_VALIDITE) AS DECIMAL) / CAST(COUNT(E.DATE_DEBUT_VALIDITE) AS DECIMAL)) AS Selectivite,
(1.0/(COUNT(DISTINCT E.DATE_DEBUT_VALIDITE))) AS Densite
FROM REF_PRE.REF.BASE_FACTURATION AS E
) A 
ORDER BY A.Selectivite DESC