-- Composition des vues du DHB
SELECT
	V.TABLE_SCHEMA + '.' + V.TABLE_NAME AS SOURCE_NAME,
	'T' AS SOURCE_TYPE,
	V.VIEW_SCHEMA  + '.' + V.VIEW_NAME AS TARGET_NAME,
	'V' AS TARGET_TYPE
FROM 
	INFORMATION_SCHEMA.VIEW_TABLE_USAGE V
WHERE 
	V.VIEW_SCHEMA != 'schema1'
	AND V.TABLE_SCHEMA != 'schema2'
	AND V.VIEW_NAME = 'maVue'
ORDER BY 
	V.VIEW_CATALOG, 
	V.VIEW_SCHEMA, 
	V.VIEW_NAME, 
	V.TABLE_CATALOG, 
	V.TABLE_SCHEMA, 
	V.TABLE_NAME